### ISSUE TITLE
Not Found for url: https://huggingface.co/google/realm-cc-news-pretrained-openqa/resolve/main/block_records.npy

### ISSUE THREAD

**Issue by Boltzmachine** [qqaatw/pytorch-realm-orqa#7]
Traceback (most recent call last):
  File "run_finetune.py", line 305, in <module>
    main(args)
  File "run_finetune.py", line 127, in main
    openqa = get_openqa(args, config)
  File "/home/chuanqi.tcq/qwk/pytorch-realm-orqa/model.py", line 99, in get_openqa
    retriever = RealmRetriever.from_pretrained(args.checkpoint_pretrained_name)
  File "/home/chuanqi.tcq/anaconda3/envs/MRC-KI/lib/python3.7/site-packages/transformers/models/realm/retrieval_realm.py", line 114, in from_pretrained
    repo_id=pretrained_model_name_or_path, filename=_REALM_BLOCK_RECORDS_FILENAME, **kwargs
  File "/home/chuanqi.tcq/anaconda3/envs/MRC-KI/lib/python3.7/site-packages/huggingface_hub/file_download.py", line 545, in hf_hub_download
    local_files_only=local_files_only,
  File "/home/chuanqi.tcq/anaconda3/envs/MRC-KI/lib/python3.7/site-packages/huggingface_hub/file_download.py", line 352, in cached_download
    r.raise_for_status()
  File "/home/chuanqi.tcq/anaconda3/envs/MRC-KI/lib/python3.7/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/google/realm-cc-news-pretrained-openqa/resolve/main/block_records.npy

**Comment by qqaatw** [comment]
Contacting with HF now.
